
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ProviderWrapper from "@/components/ProviderWrapper";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <ProviderWrapper>
      <div className="flex min-h-screen flex-col">
        <div className="flex flex-col lg:max-w-screen-xl mx-auto text-black w-full flex-grow px-6 flex-1">
          <Navbar/>
          <div className="flex flex-col flex-1">
            {children}
          </div>
          <Footer/>
        </div>
      </div>
      </ProviderWrapper>
    </body>
    </html>
  );
}
